{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.29.jar",
          "url": "injector-plugin-2.0.29.jar",
          "size": 137544,
          "sha512": "a3a644539a5ea9d8e03b690c95a35657d61e9951b72d6536a0ac111b4eaf13a3cb832cff047b86f5ada140cf06744ba86c2a9c808a77692222edd0f5a63d0fc9",
          "sha256": "c7b74c74ca8b43f223096f565a9b7dd4b7e158a578f9a1fe3e01ccecc2ac7d45",
          "sha1": "1feb324e8373d39bf6a9ceeb5a5118d437acd9ca",
          "md5": "0c050df122e75a1e30f7553857db5861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.29.jar",
          "url": "injector-plugin-2.0.29.jar",
          "size": 137544,
          "sha512": "a3a644539a5ea9d8e03b690c95a35657d61e9951b72d6536a0ac111b4eaf13a3cb832cff047b86f5ada140cf06744ba86c2a9c808a77692222edd0f5a63d0fc9",
          "sha256": "c7b74c74ca8b43f223096f565a9b7dd4b7e158a578f9a1fe3e01ccecc2ac7d45",
          "sha1": "1feb324e8373d39bf6a9ceeb5a5118d437acd9ca",
          "md5": "0c050df122e75a1e30f7553857db5861"
        }
      ]
    }
  ]
}
