{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.28.jar",
          "url": "injector-plugin-2.0.28.jar",
          "size": 137578,
          "sha512": "b73a3134e695333000c4f9d4f60413dbe396002034ba535c21f96fb5a3e0342dc78e73ffb8356b5d47efd4e87c6d1ea25b2b6445b2786213f4bdd1367d2fb958",
          "sha256": "2b535f64d9f1d3b52a8e21a07a0756469849560afef2937e7a5ba8ef582bd0d0",
          "sha1": "8a056575fc9e4a26e274835bd07f0a8bae4c27af",
          "md5": "e9c2ba8644d6166b94e11f9f9cbe0364"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.28.jar",
          "url": "injector-plugin-2.0.28.jar",
          "size": 137578,
          "sha512": "b73a3134e695333000c4f9d4f60413dbe396002034ba535c21f96fb5a3e0342dc78e73ffb8356b5d47efd4e87c6d1ea25b2b6445b2786213f4bdd1367d2fb958",
          "sha256": "2b535f64d9f1d3b52a8e21a07a0756469849560afef2937e7a5ba8ef582bd0d0",
          "sha1": "8a056575fc9e4a26e274835bd07f0a8bae4c27af",
          "md5": "e9c2ba8644d6166b94e11f9f9cbe0364"
        }
      ]
    }
  ]
}
